name: gh-pages-flutter

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - uses: subosito/flutter-action@v1
      - name: test
        run: |
          pwd
          ls -Alh
        working-directory: ./orioks/
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: ./orioks/
          targetBranch: main
          baseHref: /orioks/
